#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

__self="${BASH_SOURCE[0]}"
__dir="$(cd "$(dirname "${__self}")" > /dev/null && pwd)"
__file="${__dir}/$(basename "${__self}")"

dlurl='https://www83.zippyshare.com/v/yakMuCxe/file.html'

zippydl="$(dirname "${__dir}")/zippydl"
tmpdir="${__dir}/tmp"

export wgetb="$(which wget)"
export corsa='https://cors-anywhere.herokuapp.com'

rm -rf "${tmpdir}"
mkdir "${tmpdir}"
pushd "${tmpdir}" > /dev/null

corsa_enable() {
	local url="${corsa}/corsdemo"
	local page="$("${wgetb}" -q --content-on-error -O- "${url}" 2>&1 || true)"
	local attrs="$(grep -o 'name="accessRequest" value="[^"]*"' <<< "${page}")"
	local token="$(cut -d'"' -f4 <<< "${attrs}")"
	local geturl="${url}?accessRequest=${token}"
	"${wgetb}" -q --content-on-error --save-headers -O- "${geturl}" || true
}

echo 'Trying direct'
("${zippydl}" "${dlurl}") && true
code="$?"

if [[ "${code}" != 0 ]]; then
	echo "Re-trying: ${corsa}"
	corsa_enable
	wget () {
		local args=("$@")
		local i
		for i in "${!args[@]}"; do
			local a="${args[$i]}"
			if [[ "${a}" == 'http://'* || "${a}" == 'https://'* ]]; then
				args[$i]="${corsa}/${a}"
			fi
		done
		"${wgetb}" --header="X-Requested-With: XMLHttpRequest" "${args[@]}" >&2
	}
	export -f wget

	("${zippydl}" "${dlurl}") && true
	code="$?"
fi

if [[ "${code}" != 0 ]]; then
	echo "Failed to download: ${dlurl}"
	exit 1
fi

shasum -c "${__dir}/jmmb avatar.png.sha256"

popd > /dev/null
rm -rf "${tmpdir}"
