name: main

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    if: github.event_name != 'schedule' || github.repository == 'JrMasterModelBuilder/zippydl'
    runs-on: ubuntu-20.04
    steps:
      - name: Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: bash spec/ci.sh
        env:
          ZIPPYDL_NO_CHECK_CERTIFICATE: 1
