name: main

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Create tmp
        run: mkdir -p tmp

      - name: Copy hashsum
        run: cp 'spec/jmmb avatar.png.sha256' tmp

      - name: Download
        working-directory: tmp
        run: ../zippydl https://www83.zippyshare.com/v/yakMuCxe/file.html

      - name: Verify hashsum
        run: shasum -c 'spec/jmmb avatar.png.sha256'
